name: Build PS4 ntfonto Cache Manifest

on:
  workflow_dispatch:

  push:
    paths:
      - 'Games/PlayStation Jailbreak/PS4/ntfonto/**'
      - '.github/workflows/build-jb_ps4_ntfonto.yml'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Cache Manifest erzeugen
        run: |
          cd "Games/PlayStation Jailbreak/PS4/ntfonto"
          python3 appcache_manifest_generator.py .

      - name: Cache Manifest committen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "Games/PlayStation Jailbreak/PS4/ntfonto/cache.manifest"

          if git diff --cached --quiet; then
            echo "Keine Änderungen am cache.manifest"
          else
            git commit -m "Update ntfonto cache manifest"
            git push
          fi